name: Artificat_Composition

jobs:
  consumer:
    runs-on: ubuntu-latest
    needs: producer # name of the job to upload
  
    steps:
      - uses: ./.github/actions/verify-artifact
        with:
          artifact-name: shared-file
          path: downloaded
          expected-file: message.txt
          required: true
  
      - name: Read file
        run: cat downloaded/message.txt
